const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const elements=new Map();function el(s){if(!elements.has(s))elements.set(s,{innerHTML:'',textContent:'',value:'',classList:{add(){},remove(){}},showModal(){},close(){}});return elements.get(s)}
const ctx={console,URL,localStorage:{getItem(){return null},setItem(){}},document:{querySelector:el,querySelectorAll(){return[]},addEventListener(){},createElement(){return{click(){}}}},location:{hash:'#story'},window:{addEventListener(){}},navigator:{},setTimeout(){return 1},clearTimeout(){}};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/dist/app.js','utf8'),ctx);
vm.runInContext(`
function finish(){for(let i=0;i<10&&state.automation&&!state.automation.done;i++)advanceAutomation()}
for(const name of Object.keys(views)){if(!views[name]().length)throw Error(name)}
state=fresh();act('analyze');if(state.automation.tasks.length!==4)throw Error('Planning tasks');finish();if(automationPanel())throw Error('Completed work panel still shown');if(!state.analyzed||!state.generatedStory)throw Error('Plan missing');act('approveStory');act('approveTimeline');
document.querySelector('#shotTitle').value='Changed scene';document.querySelector('#shotDescription').value='Keep this action';act('saveShot');if(state.storyApproved||state.timelineApproved||!state.pendingRevision)throw Error('Revision gate missing');finish();if(!state.generatedStory[1].text.includes('Keep this action')||state.shotDescriptions[state.selected]!=='Keep this action')throw Error('Revision constraint lost');act('approveTimeline');if(state.timelineApproved)throw Error('Unreviewed revision approved');act('approveStory');act('approveTimeline');
state.enhancementInstruction='Keep costume';act('enhance');finish();if(!state.imageEnhancedPrompt.includes('Keep costume'))throw Error('Image enhancement');act('enhanceVideo');finish();if(!state.videoEnhancedPrompt.includes('Keep costume'))throw Error('Video enhancement');
state.orchestration='역할 고정';state.taskModels={1:'xAI · 구독 모델',4:'LM Studio · 로컬 모델'};if(assignedModel('플롯·스토리')!=='xAI · 구독 모델'||assignedModel('비디오 프롬프트 강화')!=='LM Studio · 로컬 모델')throw Error('Manual assignments');state.orchestration='Primary 자동 배정';state.settingsTab='작업 배정';if(!settingsBody().includes('disabled aria-disabled'))throw Error('Auto lock');
state.comfyScanned=true;state.comfySelectedModel=demoComfyModels[0];state.comfySelectedLoras=demoComfyLoras.slice(0,2).map(l=>l.id);act('start');finish();if(state.executionConfig.loras.length!==2||state.executionConfig.loras[0].strength!==0.7)throw Error('Selected LoRA or recommendation not applied');if(!videoProgress().includes('마지막 상태 수신'))throw Error('Video progress missing');if(!state.autoSelection||!running)throw Error('Video automation');for(let i=0;i<100&&running;i++)run();if(state.statuses[6]!=='fail'||state.statuses[7]!=='waiting')throw Error('QC gate');state.selected=6;act('retry');for(let i=0;i<10&&running;i++)run();if(state.statuses[6]!=='pass')throw Error('Retry');stop();
state=fresh();names.splice(0,names.length,...defaultNames);document.querySelector('#clipDuration').value='10';act('saveLength');finish();act('fillRemaining');finish();if(views.timeline().includes('id="shotTitle"')||views.timeline().includes('id="shotDescription"')||!state.shotDescriptions[20]||names[20]==='새 구간')throw Error('Auto added segment missing');if(totalLength()!==300||state.statuses.length!==21)throw Error('Remainder');state.selected=20;names[20]='New shot';state.shotDescriptions[20]='New text';act('moveLeft');finish();if(names[19]!=='New shot'||state.shotDescriptions[19]!=='New text')throw Error('Reorder');
state.comfyScanned=true;state.comfySelectedModel=demoComfyModels[0];state.comfySelectedLoras=['unidentified.safetensors'];if(resolveSelectedAssets().status!=='review_required')throw Error('Missing source was guessed');state.comfySelectedLoras=[];if(resolveSelectedAssets().status!=='ready')throw Error('No-LoRA generation blocked');
referenceLibrary.draft={name:'',profile:'',prompt:''};act('generateLibrary');if(referenceLibrary.draft.generated)throw Error('Empty image input accepted');act('enhanceLibrary');if(referenceLibrary.draft.prompt)throw Error('Empty enhancement accepted');state.enhancementInstruction='Keep lighting';referenceLibrary.draft.prompt='A quiet station';act('enhanceLibrary');act('generateLibrary');if(!referenceLibrary.draft.generated||referenceLibrary.draft.profile||!referenceLibrary.draft.prompt.includes('Keep lighting'))throw Error('Instruction-only generation failed');referenceLibrary.draft={profile:'',prompt:'A blue coat'};act('generateLibrary');if(!referenceLibrary.draft.generated)throw Error('Prompt-only generation blocked');
state=fresh();state.title='Project A';state.timelineApproved=true;referenceLibrary.draft={name:'Shared character',profile:'Adult character',prompt:'Portrait',generated:true};act('saveLibraryReference');if(state.imageApproved||!state.timelineApproved)throw Error('Library altered project');if(!referencePicker().includes('사용 안 함')||!views.images().includes('보관함'))throw Error('Optional library missing');save();const first=projectStore.activeId;projectStore.projects['test-b']={...fresh(),title:'Project B'};switchProject('test-b');if(state.title!=='Project B')throw Error('Switch');switchProject(first);if(state.title!=='Project A')throw Error('Restore');
`,ctx);console.log('Passed: automatic planning, constrained revision and approval gate, image/video local enhancement, manual/automatic assignment, automatic video preparation, sequential QC/retry, timeline edits, project isolation.');
